### test post account from customerID
POST {{host}}:{{port}}/customers/2/accounts
Content-Type: application/json

{
  "account_type": "saving",
  "amount": 5000
}

### test get account/customerID
GET {{host}}:{{port}}/customers/2/accounts